<?php
$name = "moi";
echo $name;
echo "<br>";
echo "<br>";
echo "exo 2";
echo "<br>";
$lastname = "last";
$firstname = "first";
$age = 6 ;
echo $lastname." ".$firstname." ".$age;
echo "<br>";
echo "<br>";
echo "exo 4";
echo "<br>";
$typeString = "string";
$typeInt = 5;
$typeBool = True ;
$typeFloat = 12.3;
echo "string ".$typeString;
echo "<br>";
echo "bool ".$typeBool;
echo "<br>";
echo "int ".$typeInt;
echo "<br>";
echo "float ".$typeFloat;
echo "<br>";
echo "<br>";
echo "exo 3";
echo "<br>";
$km = 1;
echo $km;
echo "<br>";
$km = 3;
echo $km;
echo "<br>";
$km = 125;
echo $km;
echo "<br>";
echo "<br>";
echo "exo 5";
echo "<br>";
$newInt = (int)null; 
var_dump ($newInt);
echo "<br>";
$newInt = 100000000000000000000000000000000000000000000000000000000000000000; 
echo $newInt;
echo "<br>";
echo "<br>";
echo "exo 6";
echo "<br>";
echo 'bonjour '.$name.' comment vas tu ?';
echo "<br>";
echo "<br>";
echo "exo 7";
echo "<br>";
echo  "Bonjour ".$lastname." ".$firstname.",tu as ".$age." ans";
echo "<br>";
echo "<br>";
echo "exo 8";
echo "<br>";
$calcul1 = 3+4;
$calcul2 = 5*20;
$calcul3 = 45/5;
echo $calcul1;
echo "<br>";
echo $calcul2;
echo "<br>";
echo $calcul3;
echo "<br>";
?>